services:
  postgres:
    container_name: postgresdb
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    env_file:
      - .env
    volumes:
       - postgres:/data/postgres
       - ./postgres/scanfinity_db.sql:/docker-entrypoint-initdb.d/scanfinity_db.sql:ro
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - postgres
    restart: unless-stopped

volumes:
    postgres:

networks:
  postgres:
    driver: bridge
