CREATE TABLE "Users" (
  "id" integer PRIMARY KEY,
  "username" varchar,
  "email" varchar,
  "created_at" timestamp,
  "elo" integer,
  "total_games" integer,
  "product_image" bytea,
  "password_hash" varchar,
  "password_salt" varchar
);

CREATE TABLE "Puzzles" (
  "puzzle_id" integer PRIMARY KEY,
  "lang" varchar,
  "topic" varchar,
  "difficulty" varchar,
  "size" varchar,
  "times_played" integer,
  "jsonb" json
);

CREATE TABLE "Topics" (
  "topic_id" integer PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "Games" (
  "game_id" integer PRIMARY KEY,
  "puzzle_id" integer,
  "mode_id" integer,
  "date_time" timestamptz,
  "game_duration" integer,
  "game_status" varchar
);

CREATE TABLE "GameModes" (
  "mode_id" integer PRIMARY KEY,
  "code" varchar
);

CREATE TABLE "game_players" (
  "game_player_id" integer,
  "game_id" integer,
  "score" integer,
  "is_winner" boolean
);

ALTER TABLE "Games" ADD FOREIGN KEY ("puzzle_id") REFERENCES "Puzzles" ("puzzle_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "game_players" ADD FOREIGN KEY ("game_player_id") REFERENCES "Users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "game_players" ADD FOREIGN KEY ("game_id") REFERENCES "Games" ("game_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Puzzles" ADD FOREIGN KEY ("topic_id") REFERENCES "Topics" ("topic_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Games" ADD FOREIGN KEY ("mode_id") REFERENCES "GameModes" ("mode_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Users" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

